plugin: aws_ec2

regions:
  - us-east-1

filters:
  instance-state-name: running
  "tag:Name": ["cms"]

keyed_groups:
  - prefix: tag
    key: tags.Name

compose:
  ansible_host: public_ip_address

strict: False
